### ISSUE TITLE
can this project build on windows?

### ISSUE THREAD

**Issue by keison0** [kindy/libev#1]
I want to build libev on windows,but got some trouble when I try to do this.can this project be done or do you have any good Suggestions? thanks.

**Comment by kindy** [comment]
@keison0 
this library is not made by me, I only sync it from the cvs repo.
maybe you can get help from 

* Homepage: http://software.schmorp.de/pkg/libev
* Mailinglist: libev@lists.schmorp.de
   * http://lists.schmorp.de/cgi-bin/mailman/listinfo/libev
